### ISSUE TITLE
Runtime Limiters

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1692]
Currently runtime lacks limiters in several places, e.g. limiting the number of method names in access keys.

**Comment by evgenykuzyakov** [comment]
Limiters are needed for

- [ ] Max burnt gas per view method
- [ ] Max prepaid gas per function call
- [ ] Max number of actions per receipt
- [ ] Max length of allowed method names
- [ ] Max length of a method name
- [ ] Max length of returned data
- [ ] Max contract size
- [ ] Max storage key size
- [ ] Max storage value size
- [ ] Max number of promises that a function call can create
- [ ] Max number of data dependencies
- [ ] Max number of outgoing data
- [ ] Max prepaid gas
- [ ] Max number of logs

Might need to add more

**Comment by nearmax** [comment]
* Moved this Epic to docs pipeline so that @amgando can start working on adding this information to docs, adding him to Assignees.
* Removed other issues that were under this epic (the one about splitting gas limit can be a standalone task, the other one about state splitting is in its own context and mostly related to storage).
* Changed priority to P1 since documentation has no urgency for this issue.

**Comment by amgando** [comment]
@nearmax how do you imagine this landing in the docs?

i can imagine 
- as little as a "simple list of possible errors", basically translating the code and comments into markdown and including them in some sensible location
- or as much as "samples of code that induces each error", where each error includes a short snippet that, if applied in the correct context, will repeatably induce the error (not sure if this is even possible for all of these errors)

is it one of these extremes or something entirely different?

for educational purposes, being able to repeatably induce an error is much more useful than just a list of errors (which will still be somewhat useful when they match search results of course)

**Comment by evgenykuzyakov** [comment]
@amgando 
I think we need to document limits that we have within Runtime. E.g. maximum length of key to store, or maximum size of a contract that can be deployed, etc.

Here is the configuration for different limits. Each field has inline comments. If some comments are unclear then we need to expand on them:
https://github.com/nearprotocol/nearcore/blob/9ed24269598ac1f1e8e33319c80c17faac51ba93/runtime/near-vm-logic/src/config.rs#L22

Here is the default values of these limits. We use these values in the genesis, so these are the numbers that are currently in prod (or going to be soon, once we merge staging).
https://github.com/nearprotocol/nearcore/blob/9ed24269598ac1f1e8e33319c80c17faac51ba93/runtime/near-vm-logic/src/config.rs#L116

**Comment by ilblackdragon** [comment]
@amgando @evgenykuzyakov is this finished?

**Comment by amgando** [comment]
@ilblackdragon i think so, we published to docs and NEPs.  assuming it's done
https://docs.nearprotocol.com/docs/api/vm-limits
https://github.com/nearprotocol/NEPs/issues/36

**Comment by amgando** [comment]
closing
