### ISSUE TITLE
Continuous State Sync

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#2060]
We don't want to do download all the state for the shard each time we're going to validate it. If the node running for a while, it may have up to 99% of the actual state. We want to download only such pieces of data which are absent and needed for continue validating.

Subtasks:

- [ ] Check theoretical and technical possibility.
- [ ] Understand which additional proofs we need to check.
- [ ] Request part of the state from trie.
- [ ] Apply the diff.
- [ ] GC removed nodes, decrease counters for persistent trie.

**Comment by Kouprin** [comment]
Not actual for now.
