### ISSUE TITLE
[TEST] Error: dependencies::External::keccak512

### ISSUE THREAD

**Issue by ghost** [nearprotocol/nearcore#2164]
running the test with

```sh
cargo test --all --release  
```

brings 2 test failures:

```sh
test src/dependencies.rs - dependencies::External::sha256 (line 535) ... ok
test src/dependencies.rs - dependencies::External::keccak256 (line 556) ... FAILED
test src/dependencies.rs - dependencies::External::append_action_transfer (line 344) ... ok
test src/dependencies.rs - dependencies::External::storage_has_key (line 132) ... ok
test src/dependencies.rs - dependencies::External::create_receipt (line 233) ... ok
test src/dependencies.rs - dependencies::External::keccak512 (line 577) ... FAILED
test src/dependencies.rs - dependencies::External::storage_get (line 85) ... ok
```

```sh
failures:

---- src/dependencies.rs - dependencies::External::keccak256 (line 556) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[104, 110, 58, 122, 230, 181, 215, 145, 231, 229, 49, 162, 123, 167, 177, 58, 26, 142, 129, 173, 7, 37, 9, 26, 233, 115, 64, 102, 61, 85, 10, 159]`,
 right: `[174, 42, 184, 134, 113, 104, 230, 180, 244, 77, 240, 72, 199, 42, 110, 178, 6, 168, 121, 77, 27, 183, 153, 108, 197, 171, 78, 61, 186, 133, 193, 182]`', src/dependencies.rs:9:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


---- src/dependencies.rs - dependencies::External::keccak512 (line 577) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[55, 134, 96, 137, 168, 122, 187, 95, 67, 76, 18, 122, 146, 11, 225, 106, 117, 194, 154, 157, 48, 160, 90, 146, 104, 209, 118, 126, 222, 230, 200, 125, 48, 73, 197, 236, 123, 173, 192, 197, 90, 153, 167, 121, 100, 88, 209, 240, 137, 86, 239, 41, 87, 128, 219, 249, 136, 203, 220, 109, 46, 168, 234, 190]`,
 right: `[133, 196, 48, 30, 203, 238, 194, 158, 186, 246, 118, 238, 42, 158, 212, 27, 178, 72, 90, 229, 98, 108, 195, 221, 222, 161, 96, 219, 252, 99, 2, 48, 224, 15, 95, 220, 35, 209, 27, 250, 43, 168, 250, 10, 21, 25, 97, 135, 235, 61, 5, 142, 182, 85, 36, 179, 23, 126, 161, 14, 21, 118, 180, 231]`', src/dependencies.rs:9:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Any Ideas?

(ubuntu 18.04, Hyper-V on Windows)

## Reproduction

you can narrow the test run to:

```sh
cargo test --all --doc --release  
```

EDIT: using master c2e4dc071e24e49beda71aa1895f4df5401e6759 or staging a083062f7390c8d11998156689094e2165b3ebb8

# Tasks

- [x] error cause https://github.com/nearprotocol/nearcore/issues/2164#issuecomment-589719181
- [ ] determine why local / ci tests did not catch it: #2173
- [ ] update and document dev-process and ci

**Comment by abacabadabacaba** [comment]
This bug is introduced by #2045. @k06a, did you run the tests?

**Comment by lazaridiscom** [comment]
Added task section.

**Comment by k06a** [comment]
@abacabadabacaba sure, you can check CI of the PR:

**Comment by k06a** [comment]
@abacabadabacaba sure, you can check CI of the PR:
- in `staging` branch: https://github.com/nearprotocol/nearcore/pull/2045
- in `master` branch: https://github.com/nearprotocol/nearcore/pull/2072

**Comment by abacabadabacaba** [comment]
It seems that our CI doesn't run doc tests. Did you run the tests yourself? Where do these [test](https://github.com/nearprotocol/nearcore/blob/05a82d8dd74531b21567623ab0e7e75946afea19/runtime/near-vm-logic/src/dependencies.rs#L563) [vectors](https://github.com/nearprotocol/nearcore/blob/05a82d8dd74531b21567623ab0e7e75946afea19/runtime/near-vm-logic/src/dependencies.rs#L584) come from?

**Comment by k06a** [comment]
@abacabadabacaba got it, I remember, I ran doc tests and copied result from error message (checked them manually). It's strange it is not working now.

**Comment by abacabadabacaba** [comment]
A good approach for generating such test vectors is to use a different implementation. In this case, you could install a keccak library for Python and use it to generate them from command line.

**Comment by k06a** [comment]
@abacabadabacaba agree I used an online calculator to verify manually, but copied formatted vector from the error message.

**Comment by ilblackdragon** [comment]
@k06a @abacabadabacaba is there anything that needs to be done here?

**Comment by k06a** [comment]
@ilblackdragon I can't reproduce this problem for the latest `master` and `staging` due to other errors.

**Comment by ilblackdragon** [comment]
@k06a what were other errors? Can you also retest now?

**Comment by k06a** [comment]
1. In `master`:
```
cargo test --all --release
```
```
failures:
    test_block_by_id_hash
    test_block_by_id_height
    test_block_query
    test_chunk_by_hash
    test_gas_price
    test_gas_price_by_hash
    test_genesis_config
    test_genesis_records
    test_health_fail_no_blocks
    test_health_ok
    test_invalid_genesis_records_arguments
    test_query_access_key
    test_query_access_keys

test result: FAILED. 11 passed; 13 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by k06a** [comment]
1. In `master`:
```
cargo test --all --doc --release
```
```
    Finished release [optimized] target(s) in 1.01s
   Doc-tests near-runtime-fees

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-jsonrpc-client

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-rpc-error-macro

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-store

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-chunks

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-telemetry

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests testlib

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-chain

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-crypto

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-pool

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests node-runtime

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-vm-errors

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests runtime-params-estimator

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-client

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-runtime-configs

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-vm-logic

running 17 tests
test src/dependencies.rs - dependencies::External::storage_has_key (line 132) ... ok
test src/dependencies.rs - dependencies::External::keccak256 (line 475) ... ok
test src/dependencies.rs - dependencies::External::storage_remove (line 108) ... ok
test src/dependencies.rs - dependencies::External::sha256 (line 454) ... ok
test src/dependencies.rs - dependencies::External::append_action_stake (line 293) ... ok
test src/dependencies.rs - dependencies::External::append_action_transfer (line 263) ... ok
test src/dependencies.rs - dependencies::External::create_receipt (line 152) ... ok
test src/dependencies.rs - dependencies::External::append_action_function_call (line 228) ... ok
test src/dependencies.rs - dependencies::External::append_action_create_account (line 177) ... ok
test src/dependencies.rs - dependencies::External::append_action_deploy_contract (line 199) ... ok
test src/dependencies.rs - dependencies::External::append_action_add_key_with_function_call (line 360) ... ok
test src/dependencies.rs - dependencies::External::append_action_delete_account (line 426) ... ok
test src/dependencies.rs - dependencies::External::keccak512 (line 496) ... ok
test src/dependencies.rs - dependencies::External::append_action_delete_key (line 397) ... ok
test src/dependencies.rs - dependencies::External::append_action_add_key_with_full_access (line 325) ... ok
test src/dependencies.rs - dependencies::External::storage_get (line 85) ... ok
test src/dependencies.rs - dependencies::External::storage_set (line 63) ... ok

test result: ok. 17 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests neard

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-primitives

running 1 test
test src/hash.rs - hash::hash (line 159) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-epoch-manager

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-jsonrpc

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-metrics

running 1 test
test src/lib.rs -  (line 23) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests genesis-populate

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-chain-configs

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-network

running 1 test
test src/test_utils.rs - test_utils::WaitOrTimeout (line 111) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-vm-runner

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests near-rpc-error-core

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by k06a** [comment]
I see this error persists in `staging` branch, will fix and check why not happens in master

**Comment by k06a** [comment]
Just discovered `staging` branch was deprecated.
