### ISSUE TITLE
Disable Top Level Account registration

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2292]
We should disable TLA registration unless it's done by account name `registrar`.
The goal is to have an auction later to register top level account names. 
We are not implementing that for the launch though.

I think we can allow to register accounts, which names are longer than 10 (or 32?) characters.

`registrar` account originally will be controlled by Foundation. Foundation will later deploy the naming auction contract on it.

Implementing https://github.com/nearprotocol/NEPs/pull/45

CC @kcole16

**Comment by bowenwang1996** [comment]
Does it mean all accounts will be registered with some given TLA like `near`?

**Comment by evgenykuzyakov** [comment]
@ilblackdragon Where's the NEP? We can't make changes like this without discussion

**Comment by ilblackdragon** [comment]
@bowenwang1996 Our wallet will create `.near` accounts. For any other wallets that supports us at launch we can also create TLA. Also can create long names (e.g. `base58(public_key)` for folks who are coming from "crypto" world).

Otherwise, the goal is to get to a auction contract shortly after launch and allow other TLAs.

@evgenykuzyakov Created spec change - https://github.com/nearprotocol/NEPs/pull/45

**Comment by nearmax** [comment]
Unassigning @ilblackdragon since we need to have only one assignee per https://www.notion.so/nearprotocol/PRs-Issues-Guidelines-786df10eda1848e382a6008e5ed60c32 guidelines. Adding estimate. @evgenykuzyakov please adjust estimate if it is wrong.

**Comment by evgenykuzyakov** [comment]
Adjusting estimate to 5, because it requires 3 pieces:
- Add a field to a genesis config, so the top-level account ID creation to be only allowed by `registrar`.
- Implement account creation restriction.
- Add an error to indicate that the top-level account can only be created by `registrar` account.
- Push it without breaking all tests. It might need to update all app-layer to know about the new requirement and the new error.

**Comment by evgenykuzyakov** [comment]
From @ilblackdragon 
Here are all the missing pieces that needs to be done before merge:
 - [ ] Finalize & merge the discussion https://github.com/nearprotocol/NEPs/pull/45
 - [ ] nightly tests are passing
 - [ ] nearlib errors are updated & new nearlib & near-shell are released
 - [ ] DevX accounts for this @potatodepaulo :
   - [ ] for `localnet` works correctly, among other things our examples have TLA in the instructions
   - [ ] devnet / betanet / testnet  same
 - [ ] UserX accounts for this @kcole16 :
   - [ ] Wallet creates accounts with .testnet / .betanet / .devnet prefixes

**Comment by kcole16** [comment]
@evgenykuzyakov @ilblackdragon I believe these two issues are the blockers on the app layer side. 

https://github.com/nearprotocol/near-wallet/issues/407 ([PR](https://github.com/nearprotocol/near-wallet/pull/475))
https://github.com/nearprotocol/near-shell/issues/307

**Comment by ilblackdragon** [comment]
Moving to Phase 1, as what is left not blocking release for Phase 0.

**Comment by kcole16** [comment]
Closed nearprotocol/near-wallet#407. Wallet now using TLAs that match the network

**Comment by ilblackdragon** [comment]
@kcole16 &  @potatodepaulo are we ready to rock & roll for betanet / testnet?
It seems like people are keep creating accounts without prefixes when deploying contracts - given names of the staking pool.

**Comment by ilblackdragon** [comment]
Let's switch networks on.
