### ISSUE TITLE
[Tracking] Phase 1 Protocol Changes

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2778]
The following protocol changes need to land before Phase 1 launch and also before we turn on the enforcement of the forward compatibility.
- [x] Fix of million proposal attack, see: https://github.com/nearprotocol/nearcore/issues/2610 CC @bowenwang1996 
- [x] Fix of the receipt congestion attack, see: https://github.com/nearprotocol/NEPs/issues/67 CC @evgenykuzyakov 
- [x] Re-evaluate fee estimation after @mikhailOK disabled state caching: https://github.com/nearprotocol/nearcore/pull/2770 CC @olonho 
- [ ] Add the fee for loading the contract into memory CC @olonho https://github.com/nearprotocol/nearcore/issues/2777
- [x] Overflow of gas price @bowenwang1996

**Comment by bowenwang1996** [comment]
#2770 doesn't disable state caching entirely. It disables caching of large values.

**Comment by nearmax** [comment]
@mikhailOK Can we extend the `no_cache` compiler flag to disable all caching in the state?

**Comment by bowenwang1996** [comment]
@nearmax what about https://github.com/nearprotocol/NEPs/issues/79?

**Comment by mikhailOK** [comment]
`no_cache` flag sets cache size to 1

**Comment by bowenwang1996** [comment]
@nearmax can we close this now?
