### ISSUE TITLE
Monitoring Improvements

### ISSUE THREAD

**Issue by chefsale** [nearprotocol/nearcore#2896]
We had a discussion about our current monitoring setup. We have Prometheus and Grafana running, but we aren't really using this data as it isn't fully working and descriptive enough. 

You can find the data here: http://grafana.neartest.com. 

As a high overview we have identified the following issues and improvements:
- [ ] we currently only monitor betanet, so we should also enable the used port on the other networks as well
- [ ] we need to ensure some kind of rate limiting on the status endpoint to make sure we don't get DDOSed
- [ ] we need to make sure that our dashboards are persistent, as they get deleted every time we restart the docker image
- [ ] we need to automate the creation and scaling of our current Prometheus and Grafana setup
- [ ] we need to document our current monitoring process
- [ ] we currently only monitor per node and this is good for debugging a machine, but doesn't give us a good network overview, so adding aggregates like (average, p50, p90, p95, p99) across networks, shards, components, etc.
- [ ] we should add more metrics like cache usage, garbage collection times, txs processed total, time to finality, etc.

This is a global epic for discussion of all the monitoring related things. We should split this into smaller tasks linked to this epic.

cc: @mfornet @bowenwang1996 @damons

**Comment by chefsale** [comment]
Closing this task and merging it with an existing one in near-ops.
