### ISSUE TITLE
Eth bridge

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#942]
Tracking issue for the bidirectional Ethereum <--> Near bridge.

- [ ] Ethereum header hash verification inside runtime.

- [ ] Ethereum light client contract on Near that tracks Ethereum headers.

- [ ] Implement various Ethereum utilities, such as big number, rlp, in assemblyscript.

- [ ] Expose cryptographic functions used in Ethereum from runtime.

- [ ] Near light client on Ethereum.

- [ ] Bridge contracts on Ethereum & Near.

**Comment by ilblackdragon** [comment]
This works is done in https://github.com/nearprotocol/near-bridge
